### ISSUE TITLE
Il est possible que ce site ait été piraté.

### ISSUE THREAD

**Issue by benchti** [droitauvelo/squelette#2]
![selection_261](https://cloud.githubusercontent.com/assets/663816/21751090/5e4d505c-d5c1-11e6-9fc9-aa478e7447ad.png)

**Comment by benchti** [comment]
@declic3000 contrairement à ce que je pensais cela ne date pas d'avant la migration. 
j'ai suivi la procédure pour enlever ce warning . Cela consiste à mettre en place googlewebmastertool 

Il a fallu ensuite attendre qu'il passe sur tout le site . 
mais là c'est plus inquiétant on a les résultats : 

![selection_262](https://cloud.githubusercontent.com/assets/663816/21751107/b78c6c5c-d5c1-11e6-814a-d0ae001dab95.png)

Dernière détection 16 décembre ! 

J'ai régardé les pages mentionnées mais je ne vois pas ce qui peut coincer 
Tu as une idée ?

**Comment by benchti** [comment]
Ou alors lié aux modifs du 08 décembre ? et détecté louche par google le 16 ? 
https://github.com/droitauvelo/squelette/commits/master

**Comment by declic3000** [comment]
Bonjour Benoit, je ne vois pas en quoi les modifs du 8 décembre pourrait introduire du spam ? elles ne font que nettoyer un peu le squellettes. il est vrai que j'ai réparer le moteur de recherche rapide qui contient un peu de js trés classique document.location='_spip.php?articleXXX_ mais ce n'est pas de l'injection d'url.

Je ne vois pas non plus de problème. que fait t'on ?

**Comment by benchti** [comment]
![selection_304](https://cloud.githubusercontent.com/assets/663816/22001198/bc69f81a-dc43-11e6-961c-c0d71170ca55.png)

![selection_305](https://cloud.githubusercontent.com/assets/663816/22001197/bc687e68-dc43-11e6-9250-33c9277665a3.png)

**Comment by declic3000** [comment]
Merci Benoit, tu assures.

**Comment by benchti** [comment]
Ouf voilà 

![selection_314](https://cloud.githubusercontent.com/assets/663816/22155427/a7ca2012-df2f-11e6-932a-f29f90d4f995.png)
![selection_313](https://cloud.githubusercontent.com/assets/663816/22155428/a7d151fc-df2f-11e6-805d-823da6ce76db.png)
